// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaOrders.Infrastructure.Data;

#nullable disable

namespace PizzaOrders.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PizzaOrders.Domain.Entities.AuthEntities.RefreshTokenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRevoked")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "identity");
                });

            modelBuilder.Entity("PizzaOrders.Domain.Entities.AuthEntities.RoleClaimsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "identity");
                });

            modelBuilder.Entity("PizzaOrders.Domain.Entities.AuthEntities.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "identity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "afe4bbba-0acd-47b5-a87c-bc17e46e7a04",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "19618ac9-8895-43b6-adc0-20403262448e",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("PizzaOrders.Domain.Entities.AuthEntities.UserClaimEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "identity");
                });

            modelBuilder.Entity("PizzaOrders.Domain.Entities.AuthEntities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGuest")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "identity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "41977e76-f5bc-4a75-a5f1-5a059920cdd0",
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            IsGuest = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ/n/y4nL5z0mJ6/BEiXzY3T2gR8gUaZa/tG2gR8gUaZa/tG2gR8gUaZa/tG2g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9239922b-2875-4350-a926-2184462719a4",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "54792786-684f-4d36-b605-e88912f6eb34",
                            Email = "user@example.com",
                            EmailConfirmed = true,
                            IsGuest = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@EXAMPLE.COM",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ/n/y4nL5z0mJ6/BEiXzY3T2gR8gUaZa/tG2gR8gUaZa/tG2gR8gUaZa/tG2g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e178d197-36e7-4935-a744-83a3162b77a7",
                            TwoFactorEnabled = false,
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("PizzaOrders.Domain.Entities.AuthEntities.UserLoginEntity", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "identity");
                });

            modelBuilder.Entity("PizzaOrders.Domain.Entities.AuthEntities.UserRoleEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "identity");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1,
                            Id = 0
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2,
                            Id = 0
                        });
                });

            modelBuilder.Entity("PizzaOrders.Domain.Entities.AuthEntities.UserTokenEntity", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "identity");
                });

            modelBuilder.Entity("PizzaOrders.Domain.Entities.Orders.OrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders", "domain");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(8778),
                            Status = 8,
                            TotalPrice = 12.49m,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(8779),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(8784),
                            Status = 8,
                            TotalPrice = 15.97m,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(8784),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("PizzaOrders.Domain.Entities.Orders.OrderItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemModifiers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ItemPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", "domain");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 859, DateTimeKind.Utc).AddTicks(182),
                            ItemModifiers = "{\"Size\":\"Small\",\"ExtraToppings\":[{\"ToppingId\":1,\"Quantity\":1},{\"ToppingId\":2,\"Quantity\":1}]}",
                            ItemPrice = 8.99m,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            TotalPrice = 12.49m,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 859, DateTimeKind.Utc).AddTicks(183)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 859, DateTimeKind.Utc).AddTicks(1789),
                            ItemPrice = 1.99m,
                            OrderId = 1,
                            ProductId = 12,
                            Quantity = 1,
                            TotalPrice = 1.99m,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 859, DateTimeKind.Utc).AddTicks(1790)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 859, DateTimeKind.Utc).AddTicks(1791),
                            ItemModifiers = "{\"Size\":\"Large\",\"ExtraToppings\":[]}",
                            ItemPrice = 10.99m,
                            OrderId = 2,
                            ProductId = 2,
                            Quantity = 1,
                            TotalPrice = 13.99m,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 859, DateTimeKind.Utc).AddTicks(1791)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 859, DateTimeKind.Utc).AddTicks(1794),
                            ItemPrice = 3.99m,
                            OrderId = 2,
                            ProductId = 11,
                            Quantity = 1,
                            TotalPrice = 3.99m,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 859, DateTimeKind.Utc).AddTicks(1795)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 859, DateTimeKind.Utc).AddTicks(1796),
                            ItemPrice = 1.99m,
                            OrderId = 2,
                            ProductId = 13,
                            Quantity = 1,
                            TotalPrice = 1.99m,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 859, DateTimeKind.Utc).AddTicks(1796)
                        });
                });

            modelBuilder.Entity("PizzaOrders.Domain.Entities.Payment.PaymentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gateway")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments", "domain");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 12.49m,
                            ConfirmedAt = new DateTime(2025, 11, 20, 9, 43, 24, 859, DateTimeKind.Utc).AddTicks(3308),
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 859, DateTimeKind.Utc).AddTicks(3112),
                            Gateway = "Stripe",
                            Method = 1,
                            OrderId = 1,
                            Status = 1,
                            TransactionId = "TRN001",
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 859, DateTimeKind.Utc).AddTicks(3308)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 15.97m,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 859, DateTimeKind.Utc).AddTicks(3776),
                            Gateway = "Cash",
                            Method = 0,
                            OrderId = 2,
                            Status = 0,
                            TransactionId = "TRN002",
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 859, DateTimeKind.Utc).AddTicks(3776)
                        });
                });

            modelBuilder.Entity("PizzaOrders.Domain.Entities.Products.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasToppings")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductProperties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products", "domain");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 8.99m,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(5082),
                            Description = "Classic cheese and tomato pizza",
                            HasToppings = true,
                            ImageUrl = "https://example.com/images/margherita.jpg",
                            Name = "Margherita",
                            ProductProperties = "{\"SizeOptions\":[{\"Size\":\"Small\",\"Price\":0.00},{\"Size\":\"Large\",\"Price\":3.00}],\"DefaultToppingIds\":[6],\"AvailableExtraToppingIds\":[1,2,3,4,5,6,7,8,9,10]}",
                            ProductType = 0,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(5083)
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 10.99m,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(7158),
                            Description = "Pizza with pepperoni slices",
                            HasToppings = true,
                            ImageUrl = "https://example.com/images/pepperoni.jpg",
                            Name = "Pepperoni",
                            ProductProperties = "{\"SizeOptions\":[{\"Size\":\"Small\",\"Price\":0.00},{\"Size\":\"Large\",\"Price\":3.00}],\"DefaultToppingIds\":[1],\"AvailableExtraToppingIds\":[1,2,3,4,5,6,7,8,9,10]}",
                            ProductType = 0,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(7158)
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 11.99m,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(7170),
                            Description = "Pizza with ham and pineapple",
                            HasToppings = true,
                            ImageUrl = "https://example.com/images/hawaiian.jpg",
                            Name = "Hawaiian",
                            ProductProperties = "{\"SizeOptions\":[{\"Size\":\"Small\",\"Price\":0.00},{\"Size\":\"Large\",\"Price\":3.00}],\"DefaultToppingIds\":[7,8],\"AvailableExtraToppingIds\":[1,2,3,4,5,6,7,8,9,10]}",
                            ProductType = 0,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(7170)
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 12.99m,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(7189),
                            Description = "Pizza with BBQ chicken and onions",
                            HasToppings = true,
                            ImageUrl = "https://example.com/images/bbq-chicken.jpg",
                            Name = "BBQ Chicken",
                            ProductProperties = "{\"SizeOptions\":[{\"Size\":\"Small\",\"Price\":0.00},{\"Size\":\"Large\",\"Price\":3.00}],\"DefaultToppingIds\":[3,9],\"AvailableExtraToppingIds\":[1,2,3,4,5,6,7,8,9,10]}",
                            ProductType = 0,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(7189)
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 9.99m,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(7194),
                            Description = "Pizza with mixed vegetables",
                            HasToppings = true,
                            ImageUrl = "https://example.com/images/veggie.jpg",
                            Name = "Veggie",
                            ProductProperties = "{\"SizeOptions\":[{\"Size\":\"Small\",\"Price\":0.00},{\"Size\":\"Large\",\"Price\":3.00}],\"DefaultToppingIds\":[2,3,4,5],\"AvailableExtraToppingIds\":[1,2,3,4,5,6,7,8,9,10]}",
                            ProductType = 0,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(7195)
                        },
                        new
                        {
                            Id = 6,
                            BasePrice = 13.99m,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(7200),
                            Description = "Pizza with a variety of meats",
                            HasToppings = true,
                            ImageUrl = "https://example.com/images/meat-lovers.jpg",
                            Name = "Meat Lovers",
                            ProductProperties = "{\"SizeOptions\":[{\"Size\":\"Small\",\"Price\":0.00},{\"Size\":\"Large\",\"Price\":3.00}],\"DefaultToppingIds\":[1,7,9],\"AvailableExtraToppingIds\":[1,2,3,4,5,6,7,8,9,10]}",
                            ProductType = 0,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(7200)
                        },
                        new
                        {
                            Id = 7,
                            BasePrice = 12.99m,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(7265),
                            Description = "Spicy buffalo chicken pizza",
                            HasToppings = true,
                            ImageUrl = "https://example.com/images/buffalo-chicken.jpg",
                            Name = "Buffalo Chicken",
                            ProductProperties = "{\"SizeOptions\":[{\"Size\":\"Small\",\"Price\":0.00},{\"Size\":\"Large\",\"Price\":3.00}],\"DefaultToppingIds\":[10],\"AvailableExtraToppingIds\":[1,2,3,4,5,6,7,8,9,10]}",
                            ProductType = 0,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(7265)
                        },
                        new
                        {
                            Id = 8,
                            BasePrice = 14.99m,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(7271),
                            Description = "The ultimate pizza with everything",
                            HasToppings = true,
                            ImageUrl = "https://example.com/images/supreme.jpg",
                            Name = "Supreme",
                            ProductProperties = "{\"SizeOptions\":[{\"Size\":\"Small\",\"Price\":0.00},{\"Size\":\"Large\",\"Price\":3.00}],\"DefaultToppingIds\":[1,2,3,4,5,6,7],\"AvailableExtraToppingIds\":[1,2,3,4,5,6,7,8,9,10]}",
                            ProductType = 0,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(7271)
                        },
                        new
                        {
                            Id = 9,
                            BasePrice = 11.49m,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(7277),
                            Description = "Pizza with four types of cheese",
                            HasToppings = true,
                            ImageUrl = "https://example.com/images/four-cheese.jpg",
                            Name = "Four Cheese",
                            ProductProperties = "{\"SizeOptions\":[{\"Size\":\"Small\",\"Price\":0.00},{\"Size\":\"Large\",\"Price\":3.00}],\"DefaultToppingIds\":[6],\"AvailableExtraToppingIds\":[1,2,3,4,5,6,7,8,9,10]}",
                            ProductType = 0,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(7277)
                        },
                        new
                        {
                            Id = 10,
                            BasePrice = 10.49m,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(7282),
                            Description = "Pizza with fresh mushrooms",
                            HasToppings = true,
                            ImageUrl = "https://example.com/images/mushroom.jpg",
                            Name = "Mushroom",
                            ProductProperties = "{\"SizeOptions\":[{\"Size\":\"Small\",\"Price\":0.00},{\"Size\":\"Large\",\"Price\":3.00}],\"DefaultToppingIds\":[2],\"AvailableExtraToppingIds\":[1,2,3,4,5,6,7,8,9,10]}",
                            ProductType = 0,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(7282)
                        },
                        new
                        {
                            Id = 11,
                            BasePrice = 3.99m,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(7296),
                            Description = "Crispy golden french fries",
                            HasToppings = false,
                            ImageUrl = "https://example.com/images/french-fries.jpg",
                            Name = "French Fries",
                            ProductType = 2,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(7296)
                        },
                        new
                        {
                            Id = 12,
                            BasePrice = 1.99m,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(7298),
                            Description = "Classic Coca-Cola",
                            HasToppings = false,
                            ImageUrl = "https://example.com/images/coke.jpg",
                            Name = "Coke",
                            ProductType = 1,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(7298)
                        },
                        new
                        {
                            Id = 13,
                            BasePrice = 1.99m,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(7299),
                            Description = "Lemon-lime flavored soft drink",
                            HasToppings = false,
                            ImageUrl = "https://example.com/images/sprite.jpg",
                            Name = "Sprite",
                            ProductType = 1,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(7299)
                        });
                });

            modelBuilder.Entity("PizzaOrders.Domain.Entities.Toppings.ToppingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Toppings", "domain");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(3079),
                            Description = "Spicy sausage slices",
                            Name = "Pepperoni",
                            Price = 1.50m,
                            Stock = 100,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(3292)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(3487),
                            Description = "Fresh sliced mushrooms",
                            Name = "Mushrooms",
                            Price = 1.00m,
                            Stock = 100,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(3487)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(3488),
                            Description = "Diced red onions",
                            Name = "Onions",
                            Price = 0.75m,
                            Stock = 100,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(3489)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(3490),
                            Description = "Sliced green bell peppers",
                            Name = "Green Peppers",
                            Price = 0.75m,
                            Stock = 100,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(3490)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(3491),
                            Description = "Pitted black olives",
                            Name = "Black Olives",
                            Price = 1.00m,
                            Stock = 100,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(3492)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(3493),
                            Description = "Additional mozzarella cheese",
                            Name = "Extra Cheese",
                            Price = 1.25m,
                            Stock = 100,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(3493)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(3494),
                            Description = "Smoked ham",
                            Name = "Ham",
                            Price = 1.50m,
                            Stock = 100,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(3494)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(3510),
                            Description = "Sweet pineapple chunks",
                            Name = "Pineapple",
                            Price = 1.00m,
                            Stock = 100,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(3510)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(3511),
                            Description = "Grilled BBQ chicken pieces",
                            Name = "BBQ Chicken",
                            Price = 2.00m,
                            Stock = 100,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(3511)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(3512),
                            Description = "Spicy buffalo chicken pieces",
                            Name = "Buffalo Chicken",
                            Price = 2.00m,
                            Stock = 100,
                            UpdatedAt = new DateTime(2025, 11, 20, 9, 43, 24, 858, DateTimeKind.Utc).AddTicks(3513)
                        });
                });

            modelBuilder.Entity("PizzaOrders.Domain.Entities.AuthEntities.RefreshTokenEntity", b =>
                {
                    b.HasOne("PizzaOrders.Domain.Entities.AuthEntities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PizzaOrders.Domain.Entities.AuthEntities.RoleClaimsEntity", b =>
                {
                    b.HasOne("PizzaOrders.Domain.Entities.AuthEntities.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaOrders.Domain.Entities.AuthEntities.UserClaimEntity", b =>
                {
                    b.HasOne("PizzaOrders.Domain.Entities.AuthEntities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaOrders.Domain.Entities.AuthEntities.UserLoginEntity", b =>
                {
                    b.HasOne("PizzaOrders.Domain.Entities.AuthEntities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaOrders.Domain.Entities.AuthEntities.UserRoleEntity", b =>
                {
                    b.HasOne("PizzaOrders.Domain.Entities.AuthEntities.RoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaOrders.Domain.Entities.AuthEntities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaOrders.Domain.Entities.AuthEntities.UserTokenEntity", b =>
                {
                    b.HasOne("PizzaOrders.Domain.Entities.AuthEntities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaOrders.Domain.Entities.Orders.OrderEntity", b =>
                {
                    b.HasOne("PizzaOrders.Domain.Entities.AuthEntities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PizzaOrders.Domain.Entities.Orders.OrderItemEntity", b =>
                {
                    b.HasOne("PizzaOrders.Domain.Entities.Orders.OrderEntity", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaOrders.Domain.Entities.Products.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PizzaOrders.Domain.Entities.Payment.PaymentEntity", b =>
                {
                    b.HasOne("PizzaOrders.Domain.Entities.Orders.OrderEntity", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("PizzaOrders.Domain.Entities.Payment.PaymentEntity", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PizzaOrders.Domain.Entities.Orders.OrderEntity", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payment")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
